#pylint: skip-file

from day_six import part_one_solution, locate_obstructions, locate_officer

def test_part_one_solution():
    assert part_one_solution('''
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
''') == 41
    
def test_locate_officer():
    assert locate_officer("""
                          .....
                          ##...
                          .....
                          .....
                          ..^..
                          ....#
""") == [2,4]
    
    assert locate_officer("""
                          ...
                          ^..
                          ...
                          ..#
                          ...
                          ...
""") == [0,1]

def test_locate_obstructions():
    assert locate_obstructions("""
                          .....
                          ##...
                          .....
                          .....
                          ..^..
                          ....#
""") == [[0,1],[1,1],[4,4,]]
    assert locate_obstructions("""
                          ...
                          ^..
                          ...
                          ..#
                          ...
                          ...
""") == [[3,2]]
