name: pytest-pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clear old test and lint results
        run: |
          sed -i '/### Pytest Results/,/### Pylint Results/d' README.md
          echo "### Pytest Results" >> README.md
          cat pytest_results.txt >> README.md
          echo "### Pylint Results" >> README.md
          cat pylint_results.txt >> README.md

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest and capture results
        run: |
          pytest > pytest_results.txt
          echo "### Pytest Results" >> README.md
          cat pytest_results.txt >> README.md

      - name: Run pylint and capture results
        run: |
          pylint --fail-under=8 ./ > pylint_results.txt
          echo "### Pylint Results" >> README.md
          cat pylint_results.txt >> README.md
